"""Verify the curated source publication, excluding generated bytecode and caches."""
import ast
import hashlib
import json
from pathlib import Path
import re
ROOT = Path(__file__).resolve().parents[1]
manifest = json.loads((ROOT / 'audit/FILE_MANIFEST.json').read_text())
expected = {row['path']: row for row in manifest['files']}
roots = [ROOT / name for name in manifest['managed_roots']]
actual = {str(p.relative_to(ROOT)): p for root in roots for p in root.rglob('*')
          if p.is_file() and '__pycache__' not in p.parts
          and p != ROOT / 'audit/FILE_MANIFEST.json'}
for rel in manifest.get('additional_files', []):
    actual[rel] = ROOT / rel
assert set(expected) == set(actual), {
    'missing': sorted(set(expected) - set(actual)),
    'extra': sorted(set(actual) - set(expected))}
patterns = [r'(?:sk-proj-|ghp_|github_pat_)[A-Za-z0-9_-]{15,}',
            r'-----BEGIN ' + r'.*PRIVATE ' + r'KEY-----',
            r'https?://[^\s\"\)<>]*(?:[?&](?:sig|token|X-Amz-Signature|api_key)=)[^\s\"\)<>]*']
python_files = 0
for rel, p in actual.items():
    b = p.read_bytes()
    row = expected[rel]
    assert len(b) == row['bytes'] and hashlib.sha256(b).hexdigest() == row['sha256'], rel
    assert p.suffix not in ('.blend', '.blend1', '.exr', '.npz', '.npy', '.so', '.zip', '.pfm', '.pyc'), rel
    if p.suffix == '.png':
        assert b[:8] == b'\x89PNG\r\n\x1a\n', rel
        continue
    text = b.decode('utf-8')
    for pattern in patterns:
        assert not re.search(pattern, text), ('private-content pattern', rel)
    if p.suffix == '.py':
        ast.parse(text, filename=rel)
        python_files += 1
registry = json.loads((ROOT / 'material-workspace/shared/material-production/registry.json').read_text())
ids = [m['id'] for m in registry['materials']]
assert len(ids) == len(set(ids)) == 35
assert sorted(int(x[:2]) for x in ids) == list(range(1, 36))
print(json.dumps({'pass': True, 'files': len(actual), 'python_syntax_files': python_files,
                  'material_ids': 35, 'scope': 'Curated source integrity and selection; native asset replay remains separate.'}))
