"""Representation audit. Intrinsic roughness is an existing assumed parameter.
No GGX finite-slope-variance identity or material calibration is claimed.
"""
from pathlib import Path
import json,numpy as np
from PIL import Image
from scipy.interpolate import RegularGridInterpolator
from replica_geometry import sample_native
R=Path(__file__).resolve().parents[1];rec=json.loads((R/'receipts/native_recovery.json').read_text());fields=np.load(R/'state/interior_geometry_fields.npz');a=fields['fine_axis_m'];h=fields['fine_height_m'];tool=np.load(R/'state/native_tool_state4096.npy',mmap_mode='r');table=np.load(R/'state/production_column_state.npz');base=json.loads((R/'inputs/production_native_bake.json').read_text());gate=json.loads((R/'inputs/mechanism_gates.json').read_text());H=np.empty(tool.shape,'f4')
for y in range(0,len(tool),128):H[y:y+128]=np.interp(np.asarray(tool[y:y+128],dtype='f8')*gate['source_tool_metric_max_m'],table['tool_depth_m'],table['retained_displacement_m']).astype('f4')-base['mean_removed_retained_displacement_m']
# One central quarter of coupon, refine native mesh spacing by2 without changing physical domain.
a2=np.linspace(a[256],a[768],1025);y,x=np.meshgrid(a2,a2,indexing='ij');xy=np.stack([x.ravel(),y.ravel()],axis=1);reference=sample_native(H,xy).reshape(x.shape);approx=RegularGridInterpolator((a,a),h)(xy[:,::-1]).reshape(x.shape);d=approx-reference;ry,rx=np.gradient(reference,a2,a2);ay,ax=np.gradient(approx,a2,a2);nr=np.stack([-rx,-ry,np.ones_like(rx)],axis=-1);na=np.stack([-ax,-ay,np.ones_like(ax)],axis=-1);nr/=np.linalg.norm(nr,axis=-1,keepdims=True);na/=np.linalg.norm(na,axis=-1,keepdims=True);angle=np.degrees(np.arccos(np.clip((nr*na).sum(axis=-1),-1,1)));sl=np.s_[4:-4,4:-4]
image=np.asarray(Image.open(R/'maps/production_state_roughness_native4096.png'),dtype='f4')/65535;intrinsic=base['baseline_optical_roughness'];assert intrinsic==.475;crop=image[1536:2560,1536:2560];variance=crop.astype('f8')**4-intrinsic**4
out={'scope':'Native-grid bilinear height convergence plus legacy roughness overlap audit; actual renderer basis is smooth triangles and remains a separate limit','intrinsic_roughness_retained':intrinsic,'source_roughness_range_in_coupon':[float(crop.min()),float(crop.max())],'source_roughness_mean_in_coupon':float(crop.mean()),'legacy_added_alpha_squared_range':[float(variance.min()),float(variance.max())],'native_bilinear_height_rms_error_m':float(np.sqrt(np.mean(d[sl]**2))),'native_bilinear_height_max_error_m':float(np.abs(d[sl]).max()),'maximum_height_displacement_pixels_at_current_view_upper_bound':float(np.abs(d[sl]).max()/(.028/960)),'native_bilinear_normal_rms_degrees':float(np.sqrt(np.mean(angle[sl]**2))),'native_bilinear_normal_max_degrees':float(angle[sl].max()),'model_defect':'Legacy broadening is fixed at sigma4 native texels, independent of actual mesh resolution, and therefore still counts the same resolved high-frequency relief after geometry refinement.','next_control':'Remove only the added source-height variance, retaining original intrinsic0.475 roughness and all geometry/state/other material coefficients. Explicit diagnostic control, not a calibrated BRDF result.','limits':['GGX has no finite untruncated slope second moment; the fourth-root variance rule is empirical, not an exact GGX variance composition.','The current native mesh uses smooth normals on triangles; this bilinear diagnostic does not prove exact renderer-normal agreement.','Unknown real subtexel polymer roughness is represented by the retained assumed intrinsic coefficient.'],'qualification':False};(R/'receipts/roughness_overlap_audit.json').write_text(json.dumps(out,indent=2));print(json.dumps(out,indent=2))
