"""Build one small analytic-shader data fixture. The renderer owns all captures."""
from pathlib import Path
import bpy,numpy as np,json,hashlib,sys
R=Path(__file__).resolve().parents[1];sys.path.insert(0,str(R/'source'));from analytic_shader import build_group,BlenderOps
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
old=R.parent/'plastic_native_seam_transfer';gate=json.loads((old/'receipts/actual_native_seam.json').read_text());assert gate # Parent admission separately certifies its acceptance.
b= json.loads((old/'receipts/build_r3.json').read_text());src=Path(b['source']);assert sha(src)==b['source_sha256'];a=np.load(b['array_path']);tri=a['triangles'];chart=a['chart_ids'];qorigin=np.array(b['q_encoding_origin_m']);bpy.ops.wm.open_mainfile(filepath=str(src));s=bpy.context.scene;ob=next(o for o in s.objects if o.type=='MESH');original=ob.data.materials[0]
imgpath=R.parent/'plastic_native_relief_transfer/maps/production_retained_height_native4096.png';assert sha(imgpath)=='78ad8b37255340889593dcf47180913d611ce0124e756f3dcbaac187d9eb2aee';image=bpy.data.images.load(str(imgpath));image.colorspace_settings.name='Non-Color';group=build_group(image)
materials=[]
for chartid,tangent_u,tangent_v in [(0,(1,0,0),(0,1,0)),(1,(0,1,0),(0,0,1))]:
    m=original.copy();m.name='Analytic native field / chart'+str(chartid);n=m.node_tree.nodes;l=m.node_tree.links;o=BlenderOps(n,l,image)
    attribute=n.new('ShaderNodeAttribute');attribute.attribute_name='OriginalChartLocal';add=n.new('ShaderNodeVectorMath');add.operation='ADD';add.inputs[1].default_value=tuple(qorigin);l.new(attribute.outputs['Vector'],add.inputs[0]);g=n.new('ShaderNodeGroup');g.node_tree=group;l.new(add.outputs[0],g.inputs['Original q']);g.inputs['Tangent U'].default_value=tangent_u;g.inputs['Tangent V'].default_value=tangent_v
    transform=n.new('ShaderNodeVectorTransform');transform.vector_type='NORMAL';transform.convert_from='OBJECT';transform.convert_to='WORLD';l.new(g.outputs['Normal object'],transform.inputs[0]);norm=n.new('ShaderNodeVectorMath');norm.operation='NORMALIZE';l.new(transform.outputs[0],norm.inputs[0])
    bs=next(x for x in n if x.type=='BSDF_PRINCIPLED');l.new(norm.outputs[0],bs.inputs['Normal']);av=next(x for x in n if x.type=='OUTPUT_AOV' and x.aov_name=='NormalField')
    enc=n.new('ShaderNodeVectorMath');enc.operation='SCALE';enc.inputs[3].default_value=.5;l.new(norm.outputs[0],enc.inputs[0]);plus=n.new('ShaderNodeVectorMath');plus.operation='ADD';plus.inputs[1].default_value=(.5,.5,.5);l.new(enc.outputs[0],plus.inputs[0]);l.new(plus.outputs[0],av.inputs['Color'])
    cell=o.separate(g.outputs['Native cell']);cellencoded=o.combine([o('DIVIDE',cell[0],4096),o('DIVIDE',cell[1],4096),o('ADD',o('DIVIDE',g.outputs['Native height'],80e-6),.5)]);em=next(x for x in n if x.type=='EMISSION');l.new(cellencoded,em.inputs['Color'])
    materials.append(m)
ob.data.materials.clear()
for m in materials:ob.data.materials.append(m)
ob.data.polygons.foreach_set('material_index',chart.astype('i4'));stored=np.empty(a['local_position_m'].size,'f4');ob.data.vertices.foreach_get('co',stored);assert np.array_equal(stored,a['local_position_m'].ravel());stored_tri=np.empty(tri.size,'i4');ob.data.loops.foreach_get('vertex_index',stored_tri);assert np.array_equal(stored_tri,tri.ravel());stored_q=np.empty(a['q_m'].size,'f4');ob.data.attributes['OriginalChartLocal'].data.foreach_get('vector',stored_q);assert np.array_equal(stored_q,(a['q_m']-qorigin).astype('f4').ravel());assert np.array_equal(np.array(ob.location),np.array(b['object_origin_m']));s['scope']='One analytic shader actual data test; no appearance or whole-part qualification';s['selected']=False;s.cycles.samples=1;s.cycles.use_adaptive_sampling=False;s.cycles.use_denoising=False;s.cycles.use_light_tree=False;s.render.resolution_x=128;s.render.resolution_y=128
out=R/'scenes/plastic_analytic_shader_seam_data.blend';assert not out.exists();bpy.context.preferences.filepaths.save_version=0;bpy.ops.wm.save_as_mainfile(filepath=str(out),compress=True);assert out.stat().st_size<8*2**20
receipt={**b,'source':str(out),'source_sha256':sha(out),'source_bytes':out.stat().st_size,'original_fixture':str(src),'original_fixture_sha256':sha(src),'shader_source_sha256':sha(R/'source/analytic_shader.py'),'shader_group_nodes':len(group.nodes),'height_dependency':str(imgpath),'height_sha256':sha(imgpath),'q_shader_origin_actual_f32':list(add.inputs[1].default_value),'normal_capture_semantics':'Actual analytically evaluated retained native field normal after Object-to-World NORMAL transform; socket also feeds declared Principled Normal, unused for data emission.','beauty_encoding':'RGB=(actual_native_cell_x/4096,actual_native_cell_y/4096,actual_H/80e-6+0.5)', 'inherited_position_qualification':{'receipt':str(old/'receipts/actual_native_seam.json'),'sha256':sha(old/'receipts/actual_native_seam.json'),'position_pass':gate['position_pass'],'position_max_m':gate['position_error_m']['max'],'mesh_transform_q_attribute_bitwise_equal':True},'capture_only':True,'pixel_review':False,'not_full_material_qualification':True};(R/'receipts/shader_fixture_build.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt),flush=True)
