from pathlib import Path
import numpy as np,json,time,hashlib
from ring_system_r2 import RingSystem
from run_ring_r2 import hashes
R=Path(__file__).resolve().parents[1];src=R/'data/ring8_growth6mm_probe';dest=R/'data/ring8_growth6mm_hold2ms'
if dest.exists():raise FileExistsError('Frozen continuation exists')
meta=json.loads((src/'receipt.json').read_text());raw=(src/'state.npz').read_bytes();assert hashlib.sha256(raw).hexdigest()==meta['state_sha256'];assert meta['completed'];m=RingSystem(meta['sectors'],meta['stem_increment_m']);z=np.load(src/'state.npz');q=z['q'].copy();v=z['velocity'].copy();m.bonds.damage=z['damage'].copy();m.bonds.maximum_opening=z['maximum_opening'].copy();dt=meta['dt_s'];rate=meta['damping_rate_per_s'];tau=np.exp(-rate*dt/2);E0=meta['initial_energy_J'];heat=meta['final']['damping_heat_J'];E,g,op,report=m.evaluate(q);maxerr=meta['maximum_relative_energy_error']*E0;extra=.0015;n=int(np.ceil(extra/dt));dt=extra/n;tau=np.exp(-rate*dt/2);source=hashes();trace=[];start=time.time();failure=None;print('START',json.dumps({'additional_steps':n,'dt_s':dt,'previous_time_s':meta['duration_s']}),flush=True)
try:
 for i in range(n):
  K=m.kinetic(v);v*=tau;heat+=K-m.kinetic(v);vh=v+.5*dt*m.acceleration(g);q+=dt*vh;_,_,op,_=m.evaluate(q);m.bonds.evolve(op);E,g,op,report=m.evaluate(q);v=vh+.5*dt*m.acceleration(g);K=m.kinetic(v);v*=tau;heat+=K-m.kinetic(v);K=m.kinetic(v);D=m.bonds.dissipation();err=E+K+D+heat-E0;maxerr=max(maxerr,abs(err))
  if i%max(1,n//150)==0 or i==n-1:
   d=m.bonds.damage;kind=m.ops['kind'];layer=np.array([m.metadata[int(a)]['layer'] for a,b in m.ops['pairs']]);trace.append({'time_s':meta['duration_s']+(i+1)*dt,'stored_J':E,'kinetic_J':K,'cohesive_dissipation_J':D,'damping_heat_J':heat,'balance_error_J':err,'minimum_det_F':report['minimum_det_F'],'young_fracture_points':int(np.sum((d>.01)&(kind=='fracture')&(layer==0))),'old_fracture_points':int(np.sum((d>.01)&(kind=='fracture')&(layer==1))),'birth_interface_damage_points':int(np.sum((d>.01)&(kind=='birth_interface'))),'fully_failed_points':int(np.sum(d>1-1e-12)),'free_force_N':float(np.linalg.norm(g.ravel()[m.free])),'support_force_N':float(np.linalg.norm(g.ravel()[m.fixed]))})
  if i and i%5000==0:print('PROGRESS',i,n,'elapsed',time.time()-start,'energy_error',err/E0,flush=True)
except Exception as exc:failure=type(exc).__name__+': '+str(exc)
out={'completed':failure is None and i==n-1,'failure':failure,'continued_from_state_sha256':meta['state_sha256'],'physical_coefficients_unchanged':True,'dt_s':dt,'duration_s':meta['duration_s']+extra,'damping_rate_per_s':rate,'initial_energy_J':E0,'maximum_relative_energy_error':maxerr/E0,'final':trace[-1] if trace else None,'trace':trace,'source_sha256':source,'dependencies_unchanged':source==hashes(),'elapsed_s':time.time()-start,'scope':meta['scope']};dest.mkdir(parents=True);np.savez_compressed(dest/'state.npz',q=q,q_initial=m.q0,velocity=v,damage=m.bonds.damage,maximum_opening=m.bonds.maximum_opening,pairs=m.ops['pairs'],kind=m.ops['kind'],area=m.ops['area']);out['state_sha256']=hashlib.sha256((dest/'state.npz').read_bytes()).hexdigest();(dest/'receipt.json').write_text(json.dumps(out,indent=2));(R/'receipts/ring8_growth6mm_hold2ms.json').write_text(json.dumps(out,indent=2));print('RESULT',json.dumps({k:v for k,v in out.items() if k not in ('trace','source_sha256')}),flush=True)
