import bpy,numpy as np,json,hashlib
from pathlib import Path
from mathutils import Vector
R=Path(__file__).resolve().parents[1];SRC=R.parent/'plastic_explicit_curve/height_sampling_audit/seam_revision';path=SRC/'receipts/shared_top_right_numeric_patch.npz';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();assert sha(path)=='e5ff4992fd50c0832969d93b59cf11f23fabf503e471e250532417bd7aa7f9dc';a=np.load(path);tri=a['triangles'];pos=a['local_position_m'];origin=a['origin_m'];q=a['q_m'];qorigin=q.mean(axis=0);loopnorm=a['loop_normals'];bpy.ops.wm.read_factory_settings(use_empty=True);s=bpy.context.scene
mesh=bpy.data.meshes.new('Frozen texel-conforming native-height seam');mesh.from_pydata(pos.tolist(),[],tri.tolist());mesh.update();
for f in mesh.polygons:f.use_smooth=True
uses={}
for fi,t in enumerate(tri):
 for v,w in zip(t,np.roll(t,-1)):uses.setdefault(tuple(sorted((int(v),int(w)))),[]).append(fi)
sharp_count=0
for ed in mesh.edges:
 fs=uses[tuple(sorted(ed.vertices))]
 if len(fs)==2 and not np.array_equal(a['native_cell_owner_xy'][fs[0]],a['native_cell_owner_xy'][fs[1]]):ed.use_edge_sharp=True;sharp_count+=1
mesh.update();mesh.normals_split_custom_set(loopnorm.reshape(-1,3).tolist());mesh.update();assert mesh.has_custom_normals
ob=bpy.data.objects.new('Plastic / native height / shared top-right seam',mesh);s.collection.objects.link(ob);ob.location=origin
at=mesh.attributes.new('OriginalChartLocal','FLOAT_VECTOR','POINT');at.data.foreach_set('vector',(q-qorigin).astype('f4').ravel());mesh.update()
na=mesh.attributes.new('IntendedNormalField','FLOAT_VECTOR','CORNER');na.data.foreach_set('vector',loopnorm.ravel());check=np.empty(loopnorm.size,'f4');na.data.foreach_get('vector',check);assert np.array_equal(check,loopnorm.ravel())
actualnorm=np.empty(loopnorm.size,'f4');mesh.corner_normals.foreach_get('vector',actualnorm);actualnorm=actualnorm.reshape(-1,3).astype('f8');expected=loopnorm.reshape(-1,3).astype('f8');actualnorm/=np.linalg.norm(actualnorm,axis=1)[:,None];expected/=np.linalg.norm(expected,axis=1)[:,None];angles=np.degrees(np.arctan2(np.linalg.norm(np.cross(actualnorm,expected),axis=1),np.einsum('ij,ij->i',actualnorm,expected)))
mat=bpy.data.materials.new('Internal geometry and actual shading normal data');mat.use_nodes=True;n=mat.node_tree.nodes;l=mat.node_tree.links;n.remove(n['Principled BSDF']);geo=n.new('ShaderNodeNewGeometry');attr=n.new('ShaderNodeAttribute');attr.attribute_name='OriginalChartLocal';world=pos.astype('f8')+np.array(ob.location);center=world.mean(axis=0)
def vec(op,socket,value):
 x=n.new('ShaderNodeVectorMath');x.operation=op;l.new(socket,x.inputs[0]);x.inputs[3 if op=='SCALE' else 1].default_value=value;return x
an=n.new('ShaderNodeAttribute');an.attribute_name='IntendedNormalField';tr=n.new('ShaderNodeVectorTransform');tr.vector_type='NORMAL';tr.convert_from='OBJECT';tr.convert_to='WORLD';l.new(an.outputs['Vector'],tr.inputs[0]);nn=n.new('ShaderNodeVectorMath');nn.operation='NORMALIZE';l.new(tr.outputs[0],nn.inputs[0]);bs=n.new('ShaderNodeBsdfPrincipled');bs.name='Declared future surface normal input; unused in data emission';l.new(nn.outputs[0],bs.inputs['Normal'])
sub=vec('SUBTRACT',geo.outputs['Position'],tuple(center));actual_encoding_origin=list(sub.inputs[1].default_value);pe=vec('ADD',vec('SCALE',sub.outputs[0],1000.).outputs[0],(.5,.5,.5)).outputs[0];em=n.new('ShaderNodeEmission');l.new(pe,em.inputs['Color']);l.new(em.outputs[0],n['Material Output'].inputs['Surface']);mesh.materials.append(mat)
for name,socket in [('ChartLocal',vec('ADD',vec('SCALE',attr.outputs['Vector'],1000.).outputs[0],(.5,.5,.5)).outputs[0]),('NormalField',vec('ADD',vec('SCALE',nn.outputs[0],.5).outputs[0],(.5,.5,.5)).outputs[0])]:
 av=s.view_layers[0].aovs.add();av.name=name;av.type='COLOR';out=n.new('ShaderNodeOutputAOV');out.name=name;out.aov_name=name;l.new(socket,out.inputs['Color'])
s.render.engine='CYCLES';s.cycles.use_denoising=False;s.cycles.use_light_tree=False;s.cycles.samples=1;s.cycles.use_adaptive_sampling=False;s.cycles.pixel_filter_type='BOX';s.cycles.filter_width=1;s.cycles.max_bounces=2;s.world=bpy.data.worlds.new('Black data world');s.world.use_nodes=True;s.world.node_tree.nodes['Background'].inputs[1].default_value=0
camdata=bpy.data.cameras.new('Native seam data camera');cam=bpy.data.objects.new('Plastic / native seam data camera',camdata);s.collection.objects.link(cam);cam.location=Vector(center)+Vector((.027,-.039,.0454));cam.rotation_euler=(Vector(center)-cam.location).to_track_quat('-Z','Y').to_euler();cam.data.type='ORTHO';cam.data.ortho_scale=.00048;cam.data.clip_start=1e-5;s.camera=cam;s.render.resolution_x=128;s.render.resolution_y=128;s.render.resolution_percentage=100;s.render.image_settings.file_format='PNG';s.render.image_settings.color_depth='16';s.render.dither_intensity=0;s.view_settings.view_transform='Standard';s.view_settings.look='None';s.view_settings.exposure=0;s.view_settings.gamma=1;s.unit_settings.system='METRIC';s.unit_settings.scale_length=1
(R/'scenes').mkdir(exist_ok=True);dest=R/'scenes/plastic_native_shared_seam_field_r3.blend';assert not dest.exists();bpy.context.preferences.filepaths.save_version=0;bpy.ops.wm.save_as_mainfile(filepath=str(dest),compress=True);assert dest.stat().st_size<4*2**20
m={'source':str(dest),'source_sha256':sha(dest),'bytes':dest.stat().st_size,'array_path':str(path),'array_sha256':sha(path),'position_encoding_origin_m':actual_encoding_origin,'position_encoding_scale':1000.,'q_encoding_origin_m':qorigin.tolist(),'q_encoding_scale':1000.,'object_origin_m':list(ob.location),'vertices':len(pos),'triangles':len(tri),'native_cell_boundary_sharp_edges':sharp_count,'normal_capture_semantics':'Actual interpolated float32 corner attribute, normalized after Object-to-World NORMAL transform; same socket feeds declared Principled normal input, while data emission does not test BSDF appearance.','corner_normal_attribute_bit_exact':True,'stored_custom_normal_degrees_diagnostic_only':{'max':float(angles.max()),'rms':float(np.sqrt(np.mean(angles**2)))},'camera':cam.name,'field_m':.00048,'native_patch_xy_m':.000234375,'position_gate_m':20e-9,'no_new_normal_acceptance_gate':True,'no_physical_parameters_changed':True};(R/'receipts/build_r3.json').write_text(json.dumps(m,indent=2)+'\n');print(json.dumps(m),flush=True)
