from pathlib import Path
import numpy as np,sys,json,hashlib
from scipy.spatial import cKDTree
R=Path(__file__).resolve().parents[1];SRC=R.parent/'plastic_explicit_curve/height_sampling_audit/seam_revision';assert hashlib.sha256((SRC/'source/cpu_surface_contract.py').read_bytes()).hexdigest()=='2d8642e3585abb5a87f9de1d2ead389c51405e4447fe4a75267f0f72d0a2fc73';sys.path.insert(0,str(SRC/'source'));from cpu_surface_contract import expected_world_position,expected_world_normal
actual_path,out_path=map(Path,sys.argv[1:]);meta=json.loads((R/'receipts/build_r3.json').read_text());extraction=json.loads(actual_path.with_suffix('.json').read_text());assert hashlib.sha256(actual_path.read_bytes()).hexdigest()==extraction['npz_sha256'];a=np.load(actual_path);mask=np.any(a['q']!=0,axis=2);assert mask.sum()>500;pos=(a['position'][mask].astype('f8')-.5)/meta['position_encoding_scale']+meta['position_encoding_origin_m'];q=(a['q'][mask].astype('f8')-.5)/meta['q_encoding_scale']+meta['q_encoding_origin_m'];measured=a['normal_field'][mask].astype('f8')*2-1;length=np.linalg.norm(measured,axis=1);assert np.all(length>0);measured/=length[:,None]
state=np.load(meta['array_path']);assert hashlib.sha256(Path(meta['array_path']).read_bytes()).hexdigest()==meta['array_sha256'];tri=state['triangles'];verts=state['local_position_m'].astype('f8')+meta['object_origin_m'];sq=state['q_m'];chart=np.where(abs(q[:,2]-.004)<=abs(q[:,0]-.04),0,1);hit=np.empty(len(q),'i4');dist=np.empty(len(q))
for which,uvaxis in [(0,[0,1]),(1,[1,2])]:
 sel=np.flatnonzero(chart==which);faces=np.flatnonzero(state['chart_ids']==which);uv=sq[tri[faces]][:,:,uvaxis];cent=uv.mean(axis=1);query=q[sel][:,uvaxis];tree=cKDTree(cent);_,near=tree.query(query,k=min(24,len(faces)));qs=uv[near];rhs=query[:,None,:]-qs[:,:,0];du=qs[:,:,1]-qs[:,:,0];dv=qs[:,:,2]-qs[:,:,0];den=du[:,:,0]*dv[:,:,1]-du[:,:,1]*dv[:,:,0];b1=(rhs[:,:,0]*dv[:,:,1]-rhs[:,:,1]*dv[:,:,0])/den;b2=(du[:,:,0]*rhs[:,:,1]-du[:,:,1]*rhs[:,:,0])/den;b0=1-b1-b2;inside=np.minimum.reduce([b0,b1,b2])>=-1e-3;weights=np.stack([b0,b1,b2],-1);xyz=np.einsum('nkv,nkvc->nkc',weights,verts[tri[faces[near]]]);err=np.linalg.norm(xyz-pos[sel,None,:],axis=-1);err[~inside]=np.inf;best=np.argmin(err,axis=1);assert np.isfinite(err[np.arange(len(sel)),best]).all();hit[sel]=faces[near[np.arange(len(sel)),best]];dist[sel]=err[np.arange(len(sel)),best]
assert dist.max()<20e-9,'Decoded points do not lie on the frozen explicit mesh';expected=expected_world_position(q);position_error=np.linalg.norm(pos-expected,axis=1);desired=expected_world_normal(q,state['chart_ids'][hit]);facet=np.cross(verts[tri[hit,1]]-verts[tri[hit,0]],verts[tri[hit,2]]-verts[tri[hit,0]]);facet/=np.linalg.norm(facet,axis=1)[:,None]
def angles(x,y):return np.degrees(np.arctan2(np.linalg.norm(np.cross(x,y),axis=1),np.einsum('ij,ij->i',x,y)))
def stats(x):return {'max':float(x.max()),'rms':float(np.sqrt(np.mean(x*x))),'p99':float(np.quantile(x,.99))}
r={'data_origin':'synthetic_verifier_control' if extraction.get('synthetic') else 'actual_Cycles_EXRs','actual_input_hashes':extraction['input_hashes'],'hit_pixels':int(mask.sum()),'position_error_m':stats(position_error),'position_gate_m':20e-9,'position_pass':bool(position_error.max()<=20e-9),'shader_normal_field_error_degrees':stats(angles(measured,desired)),'source_geometric_facet_error_degrees':stats(angles(facet,desired)),'actual_normal_field_lengths':[float(length.min()),float(length.max())],'hit_triangle_correspondence_distance_max_m':float(dist.max()),'normal_measurement_scope':'NormalField is actual Cycles interpolation/Object-to-World/normalization of the float32 face-corner attribute feeding the declared Principled Normal input. Data emission does not exercise its BSDF appearance. Geometric facet diagnostic is reconstructed from frozen triangles at actual decoded hits, not an additional shader pass.','no_new_normal_appearance_gate':True,'source_sha256':meta['source_sha256'],'whole_corner_and_part_qualified':False,'no_automatic_promotion':True};out_path.write_text(json.dumps(r,indent=2)+'\n');print(json.dumps(r),flush=True)
