import os,resource
os.environ['OPENBLAS_NUM_THREADS']='1';os.environ['OMP_NUM_THREADS']='1';resource.setrlimit(resource.RLIMIT_AS,(2*1024**3,2*1024**3))
import json,numpy as np,hashlib,time
from carriage import Carriage,RodHessianOperator,stability,exp,P
s=Carriage();initial_roots=np.stack([s.c.origins,s.c.targets],axis=1).copy();file=P/'data/positive_equilibrium.npz';z=np.load(file);s.x=z['x'].copy();s.theta=float(z['theta_rad']);E,g=s.evaluate(s.x);pg,lam,J,S=s.projection(g);op=RodHessianOperator(s.c,lam);st=stability(op,s,J,S);r=s.record(s.x,True,[],st);curv=max(s.c.rod.diagnostics(exp(s.c.w[i]))['max_radius_curvature'] for i in range(s.c.N));roots=np.stack([s.c.origins,s.c.targets],axis=1);controls=dict(left_roots_unchanged=np.array_equal(roots[:,0],initial_roots[:,0]),right_guide_yz_unchanged=np.array_equal(roots[:,1,1:],initial_roots[:,1,1:]),right_guide_x_equals_carriage=bool(np.all(roots[:,1,0]==s.d)),saved_geometry_bit_exact=np.array_equal(s.c.points(),z['points']),stock_ref_bit_exact=np.array_equal(s.c.ref,z['stock_lengths_m']),radius_exact=float(z['radius_m'])==s.c.radius,tension_exact=float(z['tension_N'])==s.tension,zero_plane_Hessian=op.surface.nnz==0,zero_plane_force=all(s.c.last['planes'][k]==0 for k in ['top_force_N','bottom_force_N']))
# A fresh derivative at the accepted geometry, independent of solve success.
rng=np.random.default_rng(492);v=rng.normal(size=s.x.size);v/=np.linalg.norm(v);x=s.x.copy();Hv=np.r_[op.matvec(v[:-1]),0.];eps=1e-7;ep,gp=s.evaluate(x+eps*v);jp=s.jacobian();em,gm=s.evaluate(x-eps*v);jm=s.jacobian();fd=(gp+jp.T@lam-gm-jm.T@lam)/(2*eps);s.evaluate(x);herr=float(np.linalg.norm(fd-Hv)/np.linalg.norm(Hv));egerr=float(abs((ep-em)/(2*eps)-g@v)/max(abs(g@v),1e-30));ok=bool(all(controls.values()) and st['passed'] and r['force_residual']<2e-5 and r['root_error_m']<1e-9 and r['relative_stock_error']<1e-12 and r['capsule_penetration_m']<1e-6 and curv<.1 and herr<1e-4 and egerr<1e-5)
r.update(passed=ok,controls=controls,Hessian_relative_error=herr,energy_gradient_relative_error=egerr,maximum_radius_curvature=curv,state_sha256=hashlib.sha256(file.read_bytes()).hexdigest(),scope='Independently reloaded suspended zero-twist equilibrium. Static preparation only, with no physical support-removal history or finite friction qualification.')
(P/'receipts/qualified_suspended_restart.json').write_text(json.dumps(r,indent=2));print(json.dumps({k:v for k,v in r.items() if k not in ('root_forces_N','root_torques_Nm','trace')},indent=2));assert ok
