"""Independent terminal-state audit and geometry handoff; does not render."""
import os,resource
os.environ['OPENBLAS_NUM_THREADS']='1';os.environ['OMP_NUM_THREADS']='1';resource.setrlimit(resource.RLIMIT_AS,(2*1024**3,2*1024**3))
from pathlib import Path
import argparse,json,hashlib,numpy as np
from carriage import Carriage,RodHessianOperator,stability,exp,P
ap=argparse.ArgumentParser();ap.add_argument('--state',required=True);ap.add_argument('--receipt',required=True);args=ap.parse_args();state=Path(args.state).resolve();h=json.loads(Path(args.receipt).read_text());assert h['history_accepted'] and h['passed'];z=np.load(state);s=Carriage();s.x=z['x'].copy();s.theta=float(z['theta_rad']);x=s.x.copy();E,g=s.evaluate(x);pg,lam,J,S=s.projection(g);op=RodHessianOperator(s.c,lam);st=stability(op,s,J,S);r=s.record(x,True,[],st);curv=max(s.c.rod.diagnostics(exp(s.c.w[i]))['max_radius_curvature'] for i in range(s.c.N));rng=np.random.default_rng(4902);checks=[]
for k in range(3):
 v=rng.normal(size=len(x));v/=np.linalg.norm(v);Hv=np.r_[op.matvec(v[:-1]),0.];eps=1e-7;ep,gp=s.evaluate(x+eps*v);jp=s.jacobian();em,gm=s.evaluate(x-eps*v);jm=s.jacobian();fd=(gp+jp.T@lam-gm-jm.T@lam)/(2*eps);checks.append(dict(direction=k,Hessian_relative_error=float(np.linalg.norm(fd-Hv)/np.linalg.norm(Hv)),energy_gradient_relative_error=float(abs((ep-em)/(2*eps)-g@v)/max(abs(g@v),1e-30))));s.evaluate(x)
sha=hashlib.sha256(state.read_bytes()).hexdigest();r.update(state=str(state),state_sha256=sha,derivative_checks=checks,maximum_radius_curvature=curv,geometry_bit_exact=np.array_equal(s.c.points(),z['points']),saved_sha_matches=sha==h['state_sha256'],zero_plane_Hessian=op.surface.nnz==0,finite_friction_qualified=False,spatial_refinement_qualified=False)
r['passed']=bool(r['force_residual']<2e-5 and r['root_error_m']<1e-9 and r['relative_stock_error']<1e-12 and r['capsule_penetration_m']<1e-6 and curv<.1 and st['passed'] and r['geometry_bit_exact'] and r['saved_sha_matches'] and r['zero_plane_Hessian'] and all(t['Hessian_relative_error']<1e-4 and t['energy_gradient_relative_error']<1e-5 for t in checks))
(P/'receipts/spun_candidate_independent.json').write_text(json.dumps(r,indent=2));assert r['passed'];V=P/'visible-candidate';meta=dict(fibres=19,stock_length_per_fibre_m=.0024,radius_m=s.c.radius,state=str(state),state_sha256=sha,normal_contact=dict(max_penetration_m=r['capsule_penetration_m']),maximum_length_drift=r['relative_stock_error'],root_error_m=r['root_error_m'],force_residual=r['force_residual'],stability=st,twist_rad=s.theta,twist_degrees=float(np.degrees(s.theta)),bearing_turns=s.theta/(2*np.pi),twist_turns_per_m=r['twist_turns_per_m'],dimensionless_root_twist=r['dimensionless_root_twist'],nominal_helix_angle_degrees=r['nominal_helix_angle_degrees'],actual_filament_angle_degrees=h['actual_filament_angle_degrees'],tension_N=s.tension,carriage_m=s.d,effective_tex=r['effective_tex'],total_mass_kg=r['total_mass_kg'],boundary_planes_m=None,scope='Nineteen actual fixed-stock fibres after a qualified suspended normal-contact twist history under constant benchmark tension. Uniform fibre radius and prescribed intrinsic crimp; finite sliding friction, realistic staple transport, wool calibration and spatial refinement remain unqualified. This is a spinning construction diagnostic, not a carpet material.',render_promotion_scope='May show this audited mechanical state. No wool/carpet appearance promotion before actual pixels; no full material adequacy claim.');(V/'receipts/twisted_geometry.json').write_text(json.dumps(meta,indent=2));print(json.dumps({k:v for k,v in r.items() if k not in ('trace','root_forces_N','root_torques_Nm')},indent=2))
