import os,resource
os.environ['OPENBLAS_NUM_THREADS']='1';os.environ['OMP_NUM_THREADS']='1';resource.setrlimit(resource.RLIMIT_AS,(2*1024**3,2*1024**3))
import json,time,numpy as np,hashlib
from carriage import Carriage,solve,certify_path,exp,P
B=P/'ramp09';(B/'data').mkdir(parents=True,exist_ok=True);(B/'receipts').mkdir(parents=True,exist_ok=True);prior=P/'ramp08/data/accepted_007.npz';guess=P/'ramp08/data/rejected_004.npz';h=json.loads((P/'ramp08/receipts/accepted_007.json').read_text());zp=np.load(prior);z=np.load(guess);s=Carriage();s.x=z['x'].copy();s.theta=float(z['theta_rad']);s.evaluate(s.x);start=time.monotonic()
def pending(x,theta,trace):
 f=B/'data/pending_trial.npz';tmp=f.with_suffix('.tmp.npz');np.savez_compressed(tmp,x=x,theta_rad=theta,qualified=False);os.replace(tmp,f)
r=solve(s,s.theta,wall_s=60,checkpoint=pending);work=.5*(h['torque_conjugate_Nm']+r['torque_conjugate_Nm'])*(s.theta-h['twist_rad'])+s.tension*(s.d-h['carriage_m']);de=r['stored_energy_J']-h['stored_energy_J'];gap=abs(work-de)/max(abs(work),abs(de),1e-18);cert=certify_path(zp['points'],s.c.points(),s.c.radius,s.c.ref,plane_bounds=None);curv=max(s.c.rod.diagnostics(exp(s.c.w[i]))['max_radius_curvature'] for i in range(s.c.N));good=bool(r['passed'] and cert['passed'] and gap<.02 and r['relative_stock_error']<1e-12 and r['capsule_penetration_m']<1e-6 and curv<.1);t=np.diff(s.c.points(),axis=1)/s.c.ref[:,:,None];angles=np.degrees(np.arccos(np.clip(t[:,:,0],-1,1)));r.update(history_accepted=good,step_work_J=work,stored_change_J=de,relative_work_gap=gap,endpoint_path_contact=cert,maximum_radius_curvature=curv,resume_state=str(prior),numerical_initial_guess=str(guess),bearing_turns=s.theta/(2*np.pi),actual_filament_angle_degrees=dict(median=float(np.median(angles)),p95=float(np.percentile(angles,95)),maximum=float(angles.max())),scope='Unchanged-control continuation of a positive-curvature timed-out trial. It is committed only against the latest accepted work/contact history. Normal contact only.')
name='accepted_001' if good else 'rejected_001';f=B/'data'/f'{name}.npz';np.savez_compressed(f,x=s.x,w=s.c.w,points=s.c.points(),stock_lengths_m=s.c.ref,roots=np.stack([s.c.origins,s.c.targets],axis=1),radius_m=s.c.radius,endpoint_fixed=s.c.endpoint_fixed,tension_N=s.tension,theta_rad=s.theta,carriage_m=s.d,qualified=good);r['state_sha256']=hashlib.sha256(f.read_bytes()).hexdigest();(B/'receipts'/f'{name}.json').write_text(json.dumps(r,indent=2));summary=dict(status='unchanged-control correction accepted' if good else 'unchanged-control correction unqualified',accepted_steps=int(good),latest_accepted_state=str(f if good else prior),achieved_theta_rad=s.theta if good else h['twist_rad'],attempts=[dict(name=name,accepted=good,force=r['force_residual'],gap=gap)],elapsed_s=time.monotonic()-start,cumulative_boundary_work_J=work if good else 0.,cumulative_stored_change_J=de if good else 0.,initial_state=str(prior),normal_only=True);(B/'receipts/progress.json').write_text(json.dumps(summary,indent=2));print(json.dumps({k:v for k,v in r.items() if k not in ('trace','root_forces_N','root_torques_Nm')},indent=2))
