import os,resource
os.environ['OPENBLAS_NUM_THREADS']='1';os.environ['OMP_NUM_THREADS']='1';resource.setrlimit(resource.RLIMIT_AS,(2*1024**3,2*1024**3))
from pathlib import Path
import sys,json,hashlib,numpy as np
R=Path(__file__).resolve().parents[1];P=R.parent;sys.path.insert(0,str(P/'source'))
from carriage import Carriage,solve,exp,log
z=np.load(R/'data/coarse_endpoint.npz');hc=json.loads((R/'receipts/coarse_endpoint.json').read_text());assert hc['passed'];s=Carriage();s.d=float(z['carriage_m']);s.theta=float(z['theta_rad']);s.c.clamp_twist_rad=s.theta;s.c.controls(s.d,0);C=exp(z['w']);sf=(np.arange(128)+.5)*s.L/128;sc=np.r_[0.,(np.arange(64)+.5)*s.L/64,s.L];rot=[]
for i in range(19):
 seq=np.concatenate([s.c.ends[0][None],C[i],(s.c.ends[1] if s.c.endpoint_fixed[i] else C[i,-1])[None]],axis=0);jj=np.searchsorted(sc,sf,side='right')-1;u=(sf-sc[jj])/(sc[jj+1]-sc[jj]);a=seq[jj];b=seq[jj+1];rot.append(a@exp(u[:,None]*log(np.swapaxes(a,-1,-2)@b)))
s.c.w[:]=log(np.array(rot));s.x=np.r_[s.c.w.ravel(),s.d/s.L];s.evaluate(s.x)
def pending(x,theta,trace):
 f=R/'data/refined_branch_pending.npz';tmp=f.with_suffix('.tmp.npz');np.savez_compressed(tmp,x=x,theta_rad=theta,qualified=False);os.replace(tmp,f)
r=solve(s,s.theta,wall_s=60,checkpoint=pending);r['scope']='128-segment endpoint re-equilibrated from the64-segment branch at identical physical controls. This is not committed spinning history.';np.savez_compressed(R/'data/refined_branch_endpoint.npz',x=s.x,w=s.c.w,points=s.c.points(),stock_lengths_m=s.c.ref,roots=np.stack([s.c.origins,s.c.targets],axis=1),radius_m=s.c.radius,endpoint_fixed=s.c.endpoint_fixed,tension_N=s.tension,theta_rad=s.theta,carriage_m=s.d,qualified=r['passed']);(R/'receipts/refined_branch_endpoint.json').write_text(json.dumps(r,indent=2));pc=z['points'];pf=s.c.points();common=np.empty_like(pf);common[:,::2]=pc;common[:,1::2]=.5*(pc[:,:-1]+pc[:,1:]);d=common-pf;ds=s.L/128;rms=float(np.sqrt(ds*np.sum(np.sum(d[:,:-1]**2,axis=2)+np.sum(d[:,:-1]*d[:,1:],axis=2)+np.sum(d[:,1:]**2,axis=2))/3/(19*s.L)));mx=float(np.linalg.norm(d,axis=2).max());metrics=dict(total_energy_relative_difference=abs(hc['stored_energy_J']-r['stored_energy_J'])/abs(r['stored_energy_J']),twist_torque_relative_difference=abs(hc['torque_conjugate_Nm']-r['torque_conjugate_Nm'])/abs(r['torque_conjugate_Nm']),root_reaction_L2_relative_difference=float(np.linalg.norm(np.array(hc['root_forces_N'])-np.array(r['root_forces_N']))/np.linalg.norm(r['root_forces_N'])),carriage_span_difference_m=abs(hc['carriage_m']-r['carriage_m']),material_arc_centerline_RMS_over_radius=rms/s.c.radius,material_arc_centerline_maximum_over_radius=mx/s.c.radius,capsule_penetration_difference_m=abs(hc['capsule_penetration_m']-r['capsule_penetration_m']));tol=json.loads((R/'TOLERANCES.json').read_text());checks={k:bool(v<=tol[k]) for k,v in metrics.items()};checks['both_equilibria_qualified']=bool(hc['passed'] and r['passed']);out=dict(passed=all(checks.values()),checks=checks,metrics=metrics,centerline_RMS_m=rms,centerline_maximum_m=mx,tolerance_sha256=hashlib.sha256((R/'TOLERANCES.json').read_bytes()).hexdigest(),wall_s=r['wall_s'],scope='Resolution comparison on the matched alternate endpoint branch. Does not repair the failed comparison against the accepted spinning branch or qualify an equivalent history.');(R/'receipts/matching_branch_comparison.json').write_text(json.dumps(out,indent=2));print('COMPARISON',json.dumps(out),flush=True)
