import os,resource
os.environ['OPENBLAS_NUM_THREADS']='1';os.environ['OMP_NUM_THREADS']='1';resource.setrlimit(resource.RLIMIT_AS,(2*1024**3,2*1024**3))
from pathlib import Path
import sys,json,time,hashlib,numpy as np
R=Path(__file__).resolve().parents[1];P=R.parent;sys.path.insert(0,str(P/'source'))
from carriage import Carriage,MovingRoots,solve,exp,log
TOL=json.loads((R/'TOLERANCES.json').read_text());tolsha=hashlib.sha256((R/'TOLERANCES.json').read_bytes()).hexdigest();fine_state=P/'ramp08/data/accepted_007.npz';z=np.load(fine_state);h=json.loads((P/'ramp08/receipts/accepted_007.json').read_text());assert h['history_accepted'];s=Carriage();height=s.c.fixed_axis_height;originalT=s.tension;originalmat=s.c.rod.mat;s.c=MovingRoots(19,64,plane_bounds=None);s.c.fixed_axis_height=height;s.n=s.c.w.size;s.unit=s.c.unit;s.d=float(z['carriage_m']);s.theta=float(z['theta_rad']);s.c.clamp_twist_rad=s.theta;s.c.controls(s.d,0)
# Geodesic interpolation is only an initial guess. Coarse rods retain their
# own exact material interval lengths and unchanged analytic intrinsic law.
Rf=exp(z['w']);Ra=Rf[:,::2];Rb=Rf[:,1::2];Rc=Ra@exp(.5*log(np.swapaxes(Ra,-1,-2)@Rb));s.c.w[:]=log(Rc);s.x=np.r_[s.c.w.ravel(),s.d/s.L];s.evaluate(s.x);seed=s.c.points().copy();np.savez_compressed(R/'data/interpolated_initial_guess.npz',x=s.x,points=seed,theta_rad=s.theta,qualified=False)
assert s.tension==originalT and s.c.radius==float(z['radius_m']) and np.array_equal(s.c.endpoint_fixed,z['endpoint_fixed'])
def pending(x,theta,trace):
 f=R/'data/pending.npz';tmp=f.with_suffix('.tmp.npz');np.savez_compressed(tmp,x=x,theta_rad=theta,qualified=False);os.replace(tmp,f)
 (R/'receipts/progress.json').write_text(json.dumps(dict(last=trace[-1],qualified=False)))
r=solve(s,s.theta,wall_s=90,checkpoint=pending);r.update(segments=64,reference_segments=128,tolerance_sha256=tolsha,initial_guess_classification='Geodesic frame interpolation at identical material midpoint labels, then an independent physical equilibrium solve.',peak_rss_MiB=resource.getrusage(resource.RUSAGE_SELF).ru_maxrss/1024,scope=TOL['scope']);np.savez_compressed(R/'data/coarse_endpoint.npz',x=s.x,w=s.c.w,points=s.c.points(),stock_lengths_m=s.c.ref,roots=np.stack([s.c.origins,s.c.targets],axis=1),radius_m=s.c.radius,endpoint_fixed=s.c.endpoint_fixed,tension_N=s.tension,theta_rad=s.theta,carriage_m=s.d,qualified=r['passed']);(R/'receipts/coarse_endpoint.json').write_text(json.dumps(r,indent=2))
pc=s.c.points();common=np.empty_like(z['points']);common[:,::2]=pc;common[:,1::2]=.5*(pc[:,:-1]+pc[:,1:]);delta=common-z['points'];ds=np.full(128,s.L/128);rms=float(np.sqrt(np.sum(ds[None,:]*(np.sum(delta[:,:-1]**2,axis=2)+np.sum(delta[:,:-1]*delta[:,1:],axis=2)+np.sum(delta[:,1:]**2,axis=2))/3)/(s.c.N*s.L)));maxdiff=float(np.linalg.norm(delta,axis=2).max());reaction=float(np.linalg.norm(np.array(r['root_forces_N'])-np.array(h['root_forces_N']))/np.linalg.norm(h['root_forces_N']));metrics=dict(total_energy_relative_difference=abs(r['stored_energy_J']-h['stored_energy_J'])/abs(h['stored_energy_J']),twist_torque_relative_difference=abs(r['torque_conjugate_Nm']-h['torque_conjugate_Nm'])/abs(h['torque_conjugate_Nm']),root_reaction_L2_relative_difference=reaction,carriage_span_difference_m=abs(s.d-h['carriage_m']),material_arc_centerline_RMS_over_radius=rms/s.c.radius,material_arc_centerline_maximum_over_radius=maxdiff/s.c.radius,capsule_penetration_difference_m=abs(r['capsule_penetration_m']-h['capsule_penetration_m']));checks={k:bool(v<=TOL[k]) for k,v in metrics.items()};checks.update(coarse_equilibrium_qualified=bool(r['passed']),stock_gate=r['relative_stock_error']<TOL['maximum_stock_relative_error'],contact_gate=r['capsule_penetration_m']<TOL['maximum_capsule_penetration_m'],mass_exact=r['total_mass_kg']==h['total_mass_kg'],normal_boundary_zero=s.c.plane_bounds is None)
out=dict(passed=all(checks.values()),checks=checks,metrics=metrics,centerline_RMS_m=rms,centerline_maximum_m=maxdiff,tolerance_sha256=tolsha,source_state_sha256=hashlib.sha256(fine_state.read_bytes()).hexdigest(),coarse_state_sha256=hashlib.sha256((R/'data/coarse_endpoint.npz').read_bytes()).hexdigest(),wall_s=r['wall_s'],peak_rss_MiB=r['peak_rss_MiB'],scope=TOL['scope']);(R/'receipts/comparison.json').write_text(json.dumps(out,indent=2));print('COMPARISON',json.dumps(out),flush=True)
