"""Aggregate the predeclared gates without discarding failed controls."""
from pathlib import Path
import hashlib,json,numpy as np
P=Path(__file__).resolve().parents[1];R=P/'receipts'
def read(n):return json.loads((R/n).read_text())
a=read('driven_cycle_064.json');b=read('driven_cycle_128.json');c=read('driven_cycle_128_q129.json')
def compare(a,b,stride=1):
 ar=a['rows'];br=b['rows'][stride-1::stride];assert len(ar)==len(br)
 x=np.array([r['x_m'] for r in ar]);y=np.array([r['x_m'] for r in br]);fa=np.array([r['normal_wrenches'][2] for r in ar]);fb=np.array([r['normal_wrenches'][2] for r in br]);return dict(max_center_difference_m=float(max(abs(x-y))),center_relative_to_drive_amplitude=float(max(abs(x-y))/8e-6),normal_force_relative=float(np.linalg.norm(fa-fb)/np.linalg.norm(fb)),physical_heat_relative=abs(a['physical_friction_heat_J']/b['physical_friction_heat_J']-1),work_relative=abs(a['external_work_J']/b['external_work_J']-1))
t=compare(a,b,2);s=compare(b,c);checks=dict(interface=read('symmetric_tests.json')['passed'],one_sided_cap=read('cap_switch_tests.json')['passed'],actual_history_exchange=read('driven_exchange.json')['passed'],temporal_coarse=a['passed'],temporal_fine=b['passed'],spatial_fine=c['passed'],temporal_comparison=all(v<.02 for k,v in t.items() if k!='max_center_difference_m'),spatial_comparison=all(v<.02 for k,v in s.items() if k!='max_center_difference_m'))
for x in [a,b,c]:
 x['maximum_force_residual_N']=max(abs(r['force_residual_N']) for r in x['rows']);x['minimum_one_sided_restoring_N_m']=min(min(r['one_sided_restoring_N_m']) for r in x['rows'])
record=dict(scope='Conditional symmetric two-sided rigid-span friction interface and driven cycle. No flexible spinning, wool calibration, multi-component loop contact or carpet appearance promotion.',checks=checks,passed=all(checks.values()),temporal_comparison=t,spatial_comparison=s,cycles=[{k:v for k,v in x.items() if k!='rows'} for x in [a,b,c]],preserved_failures=['exchange_tests.json: one-sided constitutive asymmetry','coupling_tests_coarse_difference_steps.json and symmetric_tests_switch_crossings.json: nonsmooth finite-difference switches','driven_cycle_016.json and driven_cycle_032.json: excess numerical work','driven_cycle_*_preparation_force_control.json: initial nominal preparation violates force gate; final current histories independently equilibrate it'],normal_energy_count=1,physical_fibres=2,rigid_stock_m=.0024,physical_radius_m=16e-6,total_cylinder_volume_m3=2*np.pi*(16e-6)**2*.0024,reference_line_stiffness_N_m2=2.5e9,friction_mu_benchmark=.3)
(R/'qualification.json').write_text(json.dumps(record,indent=2));files={str(p.relative_to(P)):dict(sha256=hashlib.sha256(p.read_bytes()).hexdigest(),bytes=p.stat().st_size) for p in P.rglob('*') if p.is_file() and p.suffix in ['.py','.json','.md','.npz','.log'] and '__pycache__' not in p.parts and p.name!='FREEZE.json'};(P/'FREEZE.json').write_text(json.dumps(files,indent=2,sort_keys=True));print(json.dumps(record,indent=2))
