"""Create documentation images and a standalone local material browser."""
import html,importlib.util,json,shutil
from pathlib import Path
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
module=importlib.util.spec_from_file_location('render_package',ROOT/'source/package_path_traced.py')
render_package=importlib.util.module_from_spec(module);module.loader.exec_module(render_package)
manifest=render_package.inspect();render_package.gallery();render_package.contacts()
specs=json.loads((ROOT/'materials/manifest.json').read_text())['materials']
out=ROOT/'docs/images/after';out.mkdir(parents=True,exist_ok=True)
for s in specs:
    with Image.open(ROOT/'path_traced/renders'/(s['id']+'_detail.png')) as im:
        im.convert('RGB').resize((640,640),Image.Resampling.LANCZOS).save(out/(s['id']+'_detail.jpg'),quality=91,subsampling=0)
for key,name in [('11_stone_and_timber','stone-and-timber'),('12_leather_and_linen','leather-and-linen'),('13_metal_and_ceramic','metal-and-ceramic')]:
    with Image.open(ROOT/'path_traced/renders'/(key+'.png')) as im:im.convert('RGB').save(out/(name+'.jpg'),quality=92,subsampling=0)
for key,name in [('14_walnut_salon','walnut-salon'),('15_oak_library','oak-library'),('16_stone_kitchen','stone-kitchen'),('17_parquet_detail','parquet-detail')]:
    with Image.open(ROOT/'path_traced/renders'/(key+'.png')) as im:im.convert('RGB').resize((1600,1200),Image.Resampling.LANCZOS).save(out/(name+'.jpg'),quality=94,subsampling=0)
shutil.copyfile(ROOT/'path_traced/CYBR_Cycles_Detail_Collection.jpg',out/'collection.jpg')
(ROOT/'path_traced/README.txt').write_text('CYBR MATERIAL / Actual Cycles renders\n\nTen close-ups at 1024 x 1024; three still-life studies at 1280 x 960.\nThree full interiors and a floor detail at 2048 x 1536.\nNative RGB16 PNG. Raw studies use 768 maximum / 128 minimum samples.\nInteriors use 512 maximum / 128 minimum with guided Cycles OpenImageDenoise.\nThe floor detail is raw. No image upscaling, sharpening or added grain.\nTen native 4K procedural surfaces. No source image inputs.\nPortable editable Blender scenes are in ../blender/.\nActual settings and file hashes: render_manifest.json.\n')
style='''*{box-sizing:border-box}body{margin:0;background:#eeebe4;color:#292c28;font:15px/1.65 system-ui,sans-serif}a{color:inherit}header,main,footer{max-width:1400px;margin:auto;padding:28px 4vw}header{display:flex;justify-content:space-between;gap:25px;border-bottom:1px solid #cccabe}nav{display:flex;gap:20px;flex-wrap:wrap}h1,h2{font-family:Georgia,serif;font-weight:400;line-height:1.1}h1{font-size:clamp(40px,5vw,74px);margin:35px 0 18px}h2{font-size:34px;margin-top:60px}.intro{max-width:680px;color:#686d62}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:30px 18px}article img{display:block;width:100%;aspect-ratio:1;object-fit:cover}article h3{font:21px Georgia,serif;margin:12px 0 5px}small{color:#71766c}select,button{font:inherit;padding:9px 12px;border:1px solid #bbbdae;border-radius:0;background:#f4f2ec;color:inherit}.controls{display:flex;align-items:center;gap:20px;margin:30px 0}img.hero{display:block;width:100%;margin-top:30px}.pairs{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:20px 0 45px}.pairs img{display:block;width:100%}.pairs figure{margin:0}.pairs figcaption{font-size:13px;color:#71766c;padding-top:8px}footer{border-top:1px solid #cccabe;color:#71766c;font-size:13px}a:focus-visible,select:focus-visible{outline:2px solid #856948;outline-offset:4px}@media(max-width:1000px){.grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:600px){header{display:block}nav{margin-top:15px}.grid{grid-template-columns:repeat(2,1fr)}.pairs{gap:8px}.controls{display:block}}'''
cards=[];pairs=[]
for s in specs:
    id=s['id'];name=s['name'].split(' / ')[0];resolution=s.get('resolution',4096)
    detail='Finite wood cut · '+str(resolution)+' px' if s.get('tiling')=='finite-cut' else 'Periodic surface · 4096 px'
    cards.append(f'<article data-id="{id}"><a class="maplink" href="path_traced/renders/{id}_detail.png"><img src="path_traced/renders/{id}_detail.png" alt="{html.escape(name)} — Cycles close-up" loading="lazy"></a><h3>{html.escape(name)}</h3><small>{detail}<br>{round(manifest[id+"_detail"].get("inspection_width_m",s["preview_diameter_m"])*1000)} mm inspection view</small></article>')
    pairs.append(f'<h3>{html.escape(name)}</h3><div class="pairs"><figure><img src="docs/images/v3_1_1/{id}_detail.jpg" alt="Previous {html.escape(name)}" loading="lazy"><figcaption>v3.1.1 / original flat close-up</figcaption></figure><figure><a href="path_traced/renders/{id}_detail.png"><img src="docs/images/after/{id}_detail.jpg" alt="Revised {html.escape(name)}" loading="lazy"></a><figcaption>Revised physical specimen / appearance comparison · {round(manifest[id+"_detail"].get("inspection_width_m",s["preview_diameter_m"])*1000)} mm view</figcaption></figure></div>')
content=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CYBR MATERIAL / Surface Library</title><style>{style}</style></head><body><header><strong>CYBR MATERIAL</strong><nav><a href="path_traced/OPEN_RENDERS.html">Path-traced scenes</a><a href="docs/IMPORT_GUIDE.md">Import guide</a><a href="docs/CRITICAL_REVIEW.md">Critical review</a></nav></header><main><h1>Natural detail.<br>Surface history.</h1><p class="intro">Full architectural interiors, individual hardwood boards and ten custom surfaces. Inspect the rooms, fine detail, source maps and changes from the previous suite.</p><a href="path_traced/OPEN_RENDERS.html"><img class="hero" src="docs/images/after/walnut-salon.jpg" alt="Full walnut parquet salon rendered in Cycles"></a><h2>The collection</h2><div class="controls"><label for="map">View</label> <select id="map"><option value="render">Cycles close-up</option><option value="BaseColor.png">Base color</option><option value="Normal_OpenGL.png">Normal +Y</option><option value="Roughness.png">Roughness</option><option value="Height.png">Height</option><option value="Metallic.png">Metallic</option><option value="WearMask.png">Wear</option><option value="Opacity.png">Opacity</option></select></div><div class="grid">{''.join(cards)}</div><h2>Before and after</h2><p class="intro">The specimen views deliberately show edges and shape, so these are appearance comparisons. Matched original surface cameras are retained in path_traced/controlled_surfaces/. Documentation JPEGs are display copies; each revised image opens its native 16-bit Cycles render. See docs/STUDY_REPAIR_REVIEW.md for limits.</p>{''.join(pairs)}</main><footer>Ten native 4K procedural materials. Wood uses a radial growth volume. Scene previews were rendered by Cycles. No source images, image upscaling or added grain.</footer><script>document.getElementById('map').addEventListener('change',event=>{{document.querySelectorAll('[data-id]').forEach(card=>{{const id=card.dataset.id;const src=event.target.value==='render'?'path_traced/renders/'+id+'_detail.png':'materials/'+id+'/'+event.target.value;card.querySelector('img').src=src;card.querySelector('a').href=src}})}});</script></body></html>'''
(ROOT/'OPEN_ME.html').write_text(content,encoding='utf-8',newline='\n')
(ROOT/'README.txt').write_text('CYBR MATERIAL\n\nOpen OPEN_ME.html to inspect the suite and before/after comparisons.\nOpen path_traced/OPEN_RENDERS.html for the genuine Cycles scenes.\nComplete documentation is in README.md and docs/IMPORT_GUIDE.md.\nKeep materials/ beside blender/ for relative texture links.\nTen native 4K procedural materials. No source image inputs.\nNo image upscaling or image-generated material inputs; not scans.\n')
print('DOCUMENTATION_AND_GALLERIES_COMPLETE',flush=True)
