from pathlib import Path
import json,numpy as np
from rod_pullback import RodCoordinates,exp,log
P=Path(__file__).resolve().parents[1];R=P/'receipts';a=json.loads((R/'contact_field_M64.json').read_text());b=json.loads((R/'contact_field_M128.json').read_text());fa=np.array([x['reaction_z_N'] for x in a['rows']]);fb=np.array([x['reaction_z_N'] for x in b['rows']]);ta=np.array([x['reaction_phi_Nm'] for x in a['rows']]);tb=np.array([x['reaction_phi_Nm'] for x in b['rows']]);metrics=dict(force_history_relative=float(np.linalg.norm(fa-fb)/np.linalg.norm(fb)),torque_history_relative=float(np.linalg.norm(ta-tb)/np.linalg.norm(tb)),work_relative=abs(a['friction_work_J']/b['friction_work_J']-1),heat_relative=abs(a['heat_J']/b['heat_J']-1),stored_difference_relative_to_work=abs(a['stored_J']-b['stored_J'])/abs(b['friction_work_J']),deviation_refinement_ratio=b['max_director_tangent_deviation_rad']/a['max_director_tangent_deviation_rad'],exact_frame_refinement_ratio=b['max_exact_frame_error_rad']/a['max_exact_frame_error_rad']);checks=dict(completed=a['status']=='completed' and b['status']=='completed',fine_tangent_max=b['max_director_tangent_deviation_rad']<.01,fine_tangent_RMS=b['RMS_director_tangent_deviation_rad']<.006,tangent_refinement=metrics['deviation_refinement_ratio']<.6,exact_frame=b['max_exact_frame_error_rad']<.0003,frame_refinement=metrics['exact_frame_refinement_ratio']<.4,force=metrics['force_history_relative']<.02,torque=metrics['torque_history_relative']<.02,work=metrics['work_relative']<.02,heat=metrics['heat_relative']<.02,stored=metrics['stored_difference_relative_to_work']<.02,ledger=max(a['ledger_relative'],b['ledger_relative'])<.02)
clamps=[]
for M,name in [(64,'three_spectral_equilibrium'),(128,'three_refined128_equilibrium')]:
 z=np.load(P/'data'/f'{name}.npz');f=RodCoordinates(segments=M);g=f.unpack(f.pack(z['roots'][:,0],exp(z['w'])));fixed=exp(np.array([0.,np.pi/2,0.]));errors=[]
 for i in range(3):
  D=f.surface(g,i,np.array([0.,.0024]))[0]
  for end in range(2):
   if end==0 or i<2:errors.append(float(np.linalg.norm(log(fixed.T@D[end]))))
 clamps.append(dict(segments=M,clamped_frame_errors_rad=errors,maximum_rad=max(errors),free_tip='No imposed orientation; one-sided three-edge reconstruction.'))
r=dict(scope='Conditional convergence of a changed contact-field discretization under one prescribed smooth roll/slide history. Not pointwise Kirchhoff equivalence or an equilibrium spinning process.',checks={k:bool(v) for k,v in checks.items()},passed=bool(all(checks.values())),metrics=metrics,fine_max_tangent_deviation_rad=b['max_director_tangent_deviation_rad'],fine_RMS_tangent_deviation_rad=b['RMS_director_tangent_deviation_rad'],fine_exact_frame_error_rad=b['max_exact_frame_error_rad'],fine_work_ledger_relative=b['ledger_relative'],runtimes_s=[a['wall_s'],b['wall_s']],max_RSS_MiB=max(a['max_RSS_MiB'],b['max_RSS_MiB']),prepared_clamp_frame_deviations=clamps,production_contact_map_qualified=False,remaining='Actual flexible spin and fixed-turn tension unload with immutable history, force/work gates and process mesh refinement.');(R/'contact_field_qualification.json').write_text(json.dumps(r,indent=2));print(json.dumps(r,indent=2))
